language: android
android:
components:
    - platform-tools
    - tools
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22
    - extra-android-support
    - build-tools-22.0.1

    - android-22
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-25
  licenses:
    - 'android-sdk-preview-license.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
sudo: required
jdk: oraclejdk8
before_script:
  - chmod +x gradlew

script:
    - ./gradlew assembleRelease
